In [2]:
# import libraries

import pandas as pd

In [4]:
# create a table manually

data = {
    "name":["nick","Rahul","Ankit"],
    "Age": [30,32,34],
    "salary":[1000,5000,10000]
}

df = pd.DataFrame(data)
df

    name  Age  salary
0   nick   30    1000
1  Rahul   32    5000
2  Ankit   34   10000

In [7]:
# reading csv and create dataframe

df = pd.read_csv("/Users/nikhilsingh/Desktop/Python-Programming/pandas datasets/orders.csv")
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5